import OpenAI from 'openai';
import { GoogleGenAI, Type, FunctionDeclaration } from '@google/genai';
import { config } from './config.js';
import { tools as internalTools, executeTool as executeInternalTool } from './tools/index.js';
import { executeMCPTool, getMCPToolsSchema } from './mcp.js';

const openai = new OpenAI({
    apiKey: config.openaiApiKey,
});

// Initialize Gemini as fallback
const ai = new GoogleGenAI({ apiKey: config.geminiApiKey });

// Security: Max iteration limit on the agent loop
const MAX_ITERATIONS = 15;

// Memory storage for Level 1 (in-memory)
const conversationHistory: OpenAI.Chat.ChatCompletionMessageParam[] = [
    { role: 'system', content: 'You are Gravity Claw, a personal AI agent running locally on the user\'s machine. You have full access to their local system via dynamic MCP Tools. If the user asks you to interact with files, run commands, or check the filesystem, YOU MUST USE THE PROVIDED TOOLS to do so. Do not decline.' }
];

// Helper to get ALL tools (internal + dynamic MCP) for OpenAI
function getAllToolsForOpenAI(): OpenAI.Chat.ChatCompletionTool[] {
    const mcpTools = getMCPToolsSchema();
    return [...internalTools, ...mcpTools] as OpenAI.Chat.ChatCompletionTool[];
}

// Helper to convert ALL tools to Gemini format
function getAllToolsForGemini() {
    return [{
        functionDeclarations: getAllToolsForOpenAI().map(t => {
            const decl: FunctionDeclaration = {
                name: t.function.name,
                description: t.function.description || '',
                parameters: t.function.parameters as any
            };
            return decl;
        })
    }];
}

// Global executor router
async function routeToolExecution(name: string, args: any): Promise<any> {
    if (name.startsWith('mcp__')) {
        return await executeMCPTool(name, args);
    } else {
        return await executeInternalTool(name, args);
    }
}

// Fallback logic using Gemini
async function handleGeminiFallback(text: string): Promise<string> {
    console.log('[Agent] ⚠️ OpenAI failed (likely quota). Falling back to Gemini...');

    // We only pass the latest prompt to Gemini for this simple fallback 
    // to avoid complex message history format translations between providers
    let iterations = 0;
    let currentInput = text;

    // Create a new session chat for Gemini to handle tool loops natively
    const chat = ai.chats.create({
        model: 'gemini-2.5-flash',
        config: {
            systemInstruction: 'You are Gravity Claw, a personal AI agent running locally on the user\'s machine. You have full access to their local system via dynamic MCP Tools. If the user asks you to interact with files, run commands, or check the filesystem, YOU MUST USE THE PROVIDED TOOLS to do so. Do not decline. IMPORTANT: If using an MCP tool, refer to it exactly by its namespaced name.',
            tools: getAllToolsForGemini()
        }
    });

    while (iterations < MAX_ITERATIONS) {
        iterations++;

        try {
            const response = await chat.sendMessage({ message: currentInput });

            // Check if Gemini wants to call tools
            if (response.functionCalls && response.functionCalls.length > 0) {
                const toolResults = [];

                for (const call of response.functionCalls) {
                    console.log(`[Agent-Gemini] Calling tool: ${call.name}`);
                    try {
                        const result = await routeToolExecution(call.name, call.args);
                        toolResults.push({
                            name: call.name,
                            response: result
                        });
                    } catch (error: any) {
                        console.error(`[Agent-Gemini] Error executing tool ${call.name}:`, error);
                        toolResults.push({
                            name: call.name,
                            response: `Error: ${error.message}`
                        });
                    }
                }

                // Pass results back to Gemini for the next iteration
                // The chat object manages the history automatically
                const nextResponse = await chat.sendMessage(toolResults as any);
                if (!nextResponse.functionCalls || nextResponse.functionCalls.length === 0) {
                    return nextResponse.text || 'No response generated by Gemini.';
                }
            } else {
                // No tools called, just return the text
                return response.text || 'No response generated by Gemini.';
            }

        } catch (error) {
            console.error('[Agent-Gemini] API Error:', error);
            return "Sorry, both primary and fallback AI services encountered an error.";
        }
    }

    return "Error: Exceeded maximum tool iterations in fallback. The agent was safely halted.";
}

export async function handleUserMessage(text: string): Promise<string> {
    // Append user input
    conversationHistory.push({ role: 'user', content: text });

    let iterations = 0;

    // Agentic Loop
    while (iterations < MAX_ITERATIONS) {
        iterations++;
        console.log(`[Agent-Loop] Iteration ${iterations}/${MAX_ITERATIONS}...`);

        try {
            const response = await openai.chat.completions.create({
                model: 'gpt-4o',
                messages: conversationHistory,
                // @ts-ignore - OpenAI types for tools
                tools: getAllToolsForOpenAI(),
                tool_choice: 'auto'
            });

            const choice = response.choices[0];
            const message = choice.message;

            // Add the assistant's message (which may contain tool use calls) to the history
            conversationHistory.push(message);

            const toolCalls = message.tool_calls || [];

            // If no tools were called, the agent is done and has responded to the user
            if (toolCalls.length === 0) {
                return message.content || 'I have completed the task, but generated no text response.';
            }

            // Execute all requested tools
            for (const toolCall of toolCalls) {
                console.log(`[Agent-OpenAI] Calling tool: ${toolCall.function.name}`);
                try {
                    const args = JSON.parse(toolCall.function.arguments);
                    const result = await routeToolExecution(toolCall.function.name, args);

                    conversationHistory.push({
                        role: 'tool',
                        tool_call_id: toolCall.id,
                        content: typeof result === 'string' ? result : JSON.stringify(result, null, 2),
                    });
                } catch (error: any) {
                    console.error(`[Agent-OpenAI] Error executing tool ${toolCall.function.name}:`, error);
                    conversationHistory.push({
                        role: 'tool',
                        tool_call_id: toolCall.id,
                        content: `Error: ${error.message}`,
                    });
                }
            }

        } catch (error: any) {
            console.error(`[Agent-OpenAI] Failed with error status: ${error?.status || 'Unknown'}`);

            // If OpenAI hits a quota error (429) or Authentication error (401), fallback to Gemini
            if (error?.status === 429 || error?.status === 401 || error?.code === 'insufficient_quota') {
                // Hand off the current user prompt to Gemini
                const fallbackResponse = await handleGeminiFallback(text);

                // Update OpenAI history so it doesn't lose context if it recovers later
                conversationHistory.push({
                    role: 'assistant',
                    content: `[Fallback Response]: ${fallbackResponse}`
                });

                return fallbackResponse;
            }

            return "Sorry, I encountered an error communicating with the AI service.";
        }
    }

    return "Error: Exceeded maximum tool iterations. The agent was safely halted.";
}
